# Generated by Django 3.2.7 on 2023-02-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='hobbie_1',
            new_name='hobby_1',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='hobbie_2',
            new_name='hobby_2',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='hobbie_3',
            new_name='hobby_3',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='hobbie_4',
            new_name='hobby_4',
        ),
    ]
