# Generated by Django 3.2.7 on 2023-02-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20230223_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AddField(
            model_name='about',
            name='cert',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
