# Generated by Django 3.2.7 on 2023-02-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('github', models.CharField(max_length=254)),
                ('website', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True,
                                            upload_to='')),
                ('code', models.TextField(blank=True, max_length=1000,
                                          null=True)),
                ('description', models.TextField(blank=True,
                                                 max_length=1000, null=True)),
            ],
        ),
    ]
