# Generated by Django 3.2.7 on 2023-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image_back',
        ),
        migrations.AddField(
            model_name='project',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
