# Generated by Django 3.2.7 on 2023-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20230218_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
