# Generated by Django 3.2.7 on 2023-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_crud'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='api',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
