# Generated by Django 3.2.7 on 2023-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='letter',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
