# Generated by Django 3.2.7 on 2023-02-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
